### ISSUE TITLE
Simplify viash-test

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash-actions#1]
Implement the necessary actions to be able to create an action somewhat like this:

```yaml
  list_components:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list_components.outputs.json }}
      cachehash: ${{ steps.sync_resources.outputs.cachehash }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - uses: viash-io/viash-actions/setup@v1

    - id: sync_resources
      uses: viash-io/viash-actions/sync-and-cache@v1
      with:
        bucket: s3://openpipelines-data/
        path: resources_test

    - id: list_components
      uses: viash-io/viash-actions/list-changed-components@v1
      with:
        base-branch: main
    # outputs a json list of component configs
  
  viash_test:
    runs-on: ubuntu-latest
    needs: list_components
    if: ${{ needs.list_components.outputs.matrix != '[]' && needs.list_components.outputs.matrix != '' }}

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list_components.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v1

    - name: Cache resources data
      uses: actions/cache@v3
      timeout-minutes: 5
      with:
        path: resources_test
        key: ${{ needs.list_components.outputs.cachehash }}

    - name: Run test
      timeout-minutes: 30
      run: |
        bin/viash test -p docker ${{ matrix.component.info.config }} \
         -c '.functionality.requirements.cpus := 2' \
         -c '.functionality.requirements.memory := "5gb"'
```
